version: "3.9"

services:
  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdjango
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver
            "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: testdjango
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  postgres_data:
